# Generated by Django 5.2.7 on 2025-10-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_reply_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RenameField(
            model_name='doctorregistrationrequest',
            old_name='pytrole',
            new_name='role',
        ),
    ]
