# Generated by Django 5.2.7 on 2025-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_doctor_degree_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistrationrequest',
            name='degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctorregistrationrequest',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
