# Generated by Django 5.2.7 on 2025-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
