# Generated by Django 5.2.7 on 2025-10-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blood_group_user_phone_number_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
