# Generated by Django 5.2.7 on 2025-10-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctorregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
