# Generated by Django 5.2.7 on 2025-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor_identity_document_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
