# Generated by Django 5.2.7 on 2025-10-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistrationrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorregistrationrequest',
            name='role',
            field=models.CharField(default='doctor', max_length=20),
        ),
    ]
