# Generated by Django 5.2.7 on 2025-10-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctorregistrationrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorregistrationrequest',
            old_name='role',
            new_name='pytrole',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
