# Generated by Django 5.2.7 on 2025-10-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_message_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.contactmessage'),
        ),
    ]
