# Generated by Django 5.2.7 on 2025-10-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_contactmessage_replied_contactmessage_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='replied',
        ),
    ]
