# Generated by Django 5.2.7 on 2025-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
