# Generated by Django 5.2.7 on 2025-11-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_doctorregistrationrequest_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistrationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
