# Generated by Django 5.2.7 on 2025-11-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_doctorregistrationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
