# Generated by Django 5.2.7 on 2025-11-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_messagereply_image_doctor_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
