# Generated by Django 5.2.7 on 2025-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_patient_phone_appointment_video_room_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_status',
            field=models.CharField(choices=[('None', 'None'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', max_length=20),
        ),
    ]
