# Generated by Django 5.2.7 on 2025-10-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
