# Generated by Django 5.2.7 on 2025-10-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_proposed_date_appointment_proposed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='proposed_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='proposed_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='proposed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
