# Generated by Django 5.2.7 on 2025-10-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_appointment_proposed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='proposed_datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
