# Generated by Django 5.2.7 on 2025-10-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_remove_appointment_proposed_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
