# Generated by Django 5.2.7 on 2025-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_report_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
