# Generated by Django 5.2.7 on 2025-11-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_report_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
