# Generated by Django 5.2.7 on 2025-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_reschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reschedule Requested', 'Reschedule Requested'), ('Reschedule Approved', 'Reschedule Approved'), ('Reschedule Rejected', 'Reschedule Rejected'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
