# Generated by Django 5.2.8 on 2025-11-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointment_original_date_appointment_original_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
